import os
import json

from glob import glob
from tqdm import tqdm
from shutil import copyfile, rmtree

from PIL import Image


class MTSDataset():
    
    def __init__(self, rm_old=True):
        
        self.root_dir = '/SegTrackDetect/data/MTSD'
        self.categories = self.get_categories()
        self.splits = ['train', 'val', 'test']
        self.img_dir = f"{self.root_dir}/images"
        self.ann_dir = f"{self.root_dir}/annotations_v1"  # old version
        self.rm_old = rm_old

           
    def convert_dataset(self):

        for split_name in self.splits:
            img_paths = sorted([f"{self.root_dir}/images/{x.rstrip()}.jpg" for x in open(
                f"{self.root_dir}/splits/{split_name}.txt")])
            print(f'Converting {split_name}, number of images: {len(img_paths)}')


            ann_paths = [f"{self.ann_dir}/{os.path.splitext(os.path.basename(img_path))[0]}.json" for img_path in img_paths]
            
            images, annos = [], []
            obj_id = 0
            for i, (img_path, ann_path) in tqdm(enumerate(zip(img_paths, ann_paths))):
                
                if not os.path.isfile(ann_path):
                    with Image.open(img_path) as im:
                        W,H = im.size
                    images.append({
                        "id": i, 
                        "file_name": os.path.abspath(img_path), 
                        "height": H, 
                        "width": W
                    })
                    continue

                with open(ann_path) as f:
                    ann = json.load(f)
                W,H = ann['width'], ann['height']
                images.append({
                    "id": i, 
                    "file_name": os.path.abspath(img_path), 
                    "height": H, 
                    "width": W
                })
                for obj_data in ann['objects']:
                    label = obj_data['label']
                    cat_id = [x['id'] for x in self.categories if x['name']==label]
                    assert len(cat_id)==1
                    cat_id = cat_id[0]
                    xmin,ymin,xmax,ymax = [obj_data['bbox'][_] for _ in ['xmin','ymin','xmax','ymax']]
                    w,h = xmax-xmin, ymax-ymin
                    annos.append({
                        "id": obj_id,
                        "image_id": i,
                        "category_id": cat_id,
                        "bbox": [int(xmin), int(ymin), int(w), int(h)],
                        "segmentation": [],
                        "area": int(w*h),
                        "iscrowd": 0
                    })
                    obj_id+=1

            annotations = {"images": images, "categories": self.categories, "annotations": annos}
            out_path = f'{self.root_dir}/{split_name}.json'
            print(f'Saving {out_path}')
            with open(out_path, 'w', encoding='utf-8') as f:
                json.dump(annotations, f, ensure_ascii=False, indent=4)

        if self.rm_old:
            rmtree(f'{self.root_dir}/annotations')
            rmtree(f'{self.root_dir}/annotations_v1')


    def get_colors(self):
        return [(106, 153, 192), (1, 207, 118), (7, 247, 192), (74, 249, 237), (213, 151, 121), (224, 191, 56), (68, 149, 234), (35, 219, 9), 
        (186, 215, 189), (198, 114, 167), (164, 182, 111), (111, 13, 161), (101, 125, 219), (79, 86, 231), (241, 226, 214), (60, 202, 157), 
        (20, 59, 6), (195, 234, 239), (242, 31, 165), (90, 42, 51), (114, 157, 32), (200, 238, 133), (37, 60, 202), (223, 25, 50), (126, 105, 79), 
        (160, 195, 234), (164, 198, 245), (24, 108, 160), (74, 55, 237), (138, 70, 215), (124, 194, 198), (147, 239, 209), (86, 68, 238), (135, 208, 40), 
        (71, 48, 8), (16, 10, 153), (254, 203, 161), (101, 203, 167), (22, 252, 229), (93, 124, 199), (138, 250, 150), (77, 213, 199), (191, 186, 189), 
        (154, 41, 139), (123, 101, 150), (149, 192, 34), (99, 215, 175), (103, 147, 11), (162, 91, 158), (195, 22, 202), (77, 70, 224), (254, 245, 184), 
        (76, 118, 27), (126, 250, 215), (105, 52, 150), (163, 158, 1), (136, 204, 224), (75, 164, 172), (100, 234, 232), (148, 209, 40), (251, 93, 34), 
        (27, 178, 187), (142, 21, 195), (170, 222, 225), (161, 183, 233), (210, 51, 250), (235, 188, 9), (16, 31, 116), (155, 11, 156), (43, 80, 226), 
        (120, 77, 235), (71, 98, 180), (58, 240, 64), (136, 180, 249), (158, 118, 41), (2, 96, 202), (198, 152, 242), (110, 172, 250), (100, 187, 63), 
        (67, 235, 147), (212, 130, 237), (90, 197, 93), (65, 181, 210), (196, 190, 44), (127, 166, 199), (110, 18, 23), (145, 115, 23), (142, 15, 108), 
        (144, 176, 232), (192, 27, 138), (25, 34, 169), (92, 176, 166), (43, 252, 252), (103, 189, 40), (18, 214, 179), (125, 129, 11), (209, 41, 240), 
        (250, 98, 201), (149, 251, 96), (129, 127, 114), (59, 91, 81), (81, 194, 29), (74, 61, 245), (75, 43, 61), (111, 226, 8), (31, 253, 148), 
        (180, 253, 23), (2, 244, 42), (4, 11, 178), (160, 75, 15), (198, 136, 92), (121, 70, 69), (66, 18, 54), (10, 120, 65), (179, 11, 66), (229, 28, 128), 
        (137, 131, 198), (85, 223, 99), (130, 64, 237), (70, 17, 111), (12, 21, 63), (195, 210, 234), (188, 234, 104), (1, 240, 73), (165, 194, 118), 
        (138, 23, 244), (104, 98, 110), (37, 162, 74), (238, 152, 66), (135, 250, 22), (241, 101, 74), (54, 81, 102), (216, 17, 165), (123, 218, 137), 
        (167, 188, 32), (79, 91, 187), (76, 120, 182), (23, 21, 30), (193, 115, 243), (198, 151, 112), (5, 128, 97), (250, 141, 87), (184, 251, 155), 
        (101, 237, 213), (23, 231, 221), (47, 26, 211), (160, 213, 13), (104, 226, 33), (247, 190, 203), (160, 115, 74), (228, 168, 114), (28, 104, 93), 
        (5, 229, 18), (82, 18, 8), (153, 210, 118), (50, 102, 114), (11, 134, 20), (157, 197, 241), (103, 137, 217), (239, 253, 174), (23, 94, 62), 
        (194, 100, 225), (205, 79, 177), (29, 46, 131), (50, 192, 193), (91, 140, 95), (222, 140, 64), (45, 120, 69), (130, 186, 32), (185, 249, 25), 
        (31, 93, 50), (112, 20, 103), (116, 214, 251), (102, 177, 48), (108, 238, 181), (2, 93, 49), (250, 208, 179), (175, 23, 64), (119, 155, 197), 
        (3, 223, 68), (52, 52, 28), (224, 215, 152), (30, 207, 44), (207, 190, 113), (231, 82, 239), (18, 91, 178), (135, 38, 153), (192, 112, 4), 
        (81, 62, 197), (110, 232, 199), (33, 248, 203), (121, 189, 141), (212, 84, 188), (245, 41, 161), (26, 223, 93), (164, 52, 158), (209, 98, 25), 
        (237, 194, 20), (170, 134, 35), (202, 177, 74), (45, 93, 231), (126, 137, 169), (158, 221, 186), (98, 94, 183), (1, 126, 131), (127, 96, 222), 
        (180, 14, 20), (65, 114, 71), (127, 26, 46), (88, 165, 1), (0, 56, 9), (216, 108, 159), (193, 241, 211), (202, 221, 171), (59, 199, 127), 
        (253, 233, 87), (55, 236, 122), (162, 93, 213), (157, 129, 83), (153, 93, 104), (99, 10, 94), (73, 215, 182), (197, 219, 158), (144, 110, 26), 
        (102, 132, 106), (147, 167, 155), (162, 217, 35), (109, 220, 21), (142, 254, 140), (5, 162, 252), (80, 102, 189), (123, 161, 225), (167, 169, 222), 
        (128, 158, 150), (179, 52, 214), (78, 234, 86), (87, 25, 145), (44, 241, 48), (171, 139, 69), (3, 52, 63), (23, 109, 116), (149, 247, 115), 
        (183, 37, 70), (193, 58, 91), (97, 232, 220), (112, 77, 245), (160, 2, 122), (26, 133, 122), (95, 220, 121), (121, 129, 136), (183, 41, 190), 
        (0, 67, 234), (71, 103, 76), (46, 172, 227), (178, 188, 202), (229, 32, 142), (40, 159, 50), (88, 152, 124), (89, 153, 181), (72, 145, 123), 
        (234, 54, 138), (204, 4, 102), (85, 15, 168), (108, 97, 130), (188, 180, 120), (127, 0, 52), (127, 2, 67), (226, 158, 211), (165, 85, 135), 
        (96, 182, 118), (88, 254, 162), (147, 71, 121), (67, 155, 26), (246, 144, 35), (86, 118, 28), (235, 29, 161), (122, 21, 100), (106, 28, 71), 
        (130, 96, 121), (164, 168, 209), (105, 210, 116), (105, 18, 9), (235, 122, 74), (119, 111, 80), (216, 44, 199), (144, 8, 22), (123, 196, 75), 
        (29, 26, 158), (235, 219, 226), (191, 77, 116), (139, 85, 75), (11, 25, 146), (253, 66, 171), (93, 226, 144), (136, 115, 20), (130, 70, 138), 
        (146, 239, 139), (253, 4, 253), (97, 171, 134), (159, 147, 55), (251, 94, 248), (62, 210, 209), (223, 97, 4), (24, 161, 22), (208, 233, 44), 
        (63, 233, 154), (237, 128, 17), (7, 45, 109), (26, 163, 13), (18, 191, 168), (129, 142, 123), (229, 34, 187), (121, 81, 9), (20, 26, 104)]



    def get_categories(self):
        return [{'id': 0,
                  'name': 'warning--double-curve-first-right--g2',
                  'supercategory': 'warning'},
                 {'id': 1,
                  'name': 'regulatory--turn-left-ahead--g1',
                  'supercategory': 'regulatory'},
                 {'id': 2,
                  'name': 'complementary--obstacle-delineator--g2',
                  'supercategory': 'complementary'},
                 {'id': 3,
                  'name': 'information--telephone--g1',
                  'supercategory': 'information'},
                 {'id': 4,
                  'name': 'regulatory--end-of-bicycles-only--g1',
                  'supercategory': 'regulatory'},
                 {'id': 5,
                  'name': 'information--road-bump--g1',
                  'supercategory': 'information'},
                 {'id': 6, 'name': 'warning--children--g5', 'supercategory': 'warning'},
                 {'id': 7,
                  'name': 'regulatory--no-heavy-goods-vehicles--g1',
                  'supercategory': 'regulatory'},
                 {'id': 8,
                  'name': 'regulatory--no-pedestrians--g2',
                  'supercategory': 'regulatory'},
                 {'id': 9,
                  'name': 'regulatory--end-of-maximum-speed-limit-70--g1',
                  'supercategory': 'regulatory'},
                 {'id': 10,
                  'name': 'regulatory--radar-enforced--g1',
                  'supercategory': 'regulatory'},
                 {'id': 11, 'name': 'warning--uneven-road--g1', 'supercategory': 'warning'},
                 {'id': 12,
                  'name': 'regulatory--weight-limit--g1',
                  'supercategory': 'regulatory'},
                 {'id': 13,
                  'name': 'regulatory--bicycles-only--g3',
                  'supercategory': 'regulatory'},
                 {'id': 14,
                  'name': 'complementary--buses--g1',
                  'supercategory': 'complementary'},
                 {'id': 15,
                  'name': 'warning--divided-highway-ends--g2',
                  'supercategory': 'warning'},
                 {'id': 16, 'name': 'warning--curve-left--g2', 'supercategory': 'warning'},
                 {'id': 17,
                  'name': 'warning--horizontal-alignment-left--g1',
                  'supercategory': 'warning'},
                 {'id': 18,
                  'name': 'information--parking--g3',
                  'supercategory': 'information'},
                 {'id': 19,
                  'name': 'regulatory--buses-only--g1',
                  'supercategory': 'regulatory'},
                 {'id': 20,
                  'name': 'regulatory--left-turn-yield-on-green--g1',
                  'supercategory': 'regulatory'},
                 {'id': 21,
                  'name': 'complementary--go-left--g1',
                  'supercategory': 'complementary'},
                 {'id': 22,
                  'name': 'regulatory--no-stopping--g2',
                  'supercategory': 'regulatory'},
                 {'id': 23, 'name': 'warning--children--g2', 'supercategory': 'warning'},
                 {'id': 24,
                  'name': 'complementary--trucks--g1',
                  'supercategory': 'complementary'},
                 {'id': 25,
                  'name': 'warning--traffic-signals--g2',
                  'supercategory': 'warning'},
                 {'id': 26,
                  'name': 'regulatory--no-bicycles--g1',
                  'supercategory': 'regulatory'},
                 {'id': 27,
                  'name': 'regulatory--no-left-turn--g2',
                  'supercategory': 'regulatory'},
                 {'id': 28,
                  'name': 'information--hospital--g1',
                  'supercategory': 'information'},
                 {'id': 29,
                  'name': 'regulatory--lane-control--g1',
                  'supercategory': 'regulatory'},
                 {'id': 30,
                  'name': 'information--tram-bus-stop--g2',
                  'supercategory': 'information'},
                 {'id': 31,
                  'name': 'regulatory--turn-left--g1',
                  'supercategory': 'regulatory'},
                 {'id': 32,
                  'name': 'regulatory--no-u-turn--g2',
                  'supercategory': 'regulatory'},
                 {'id': 33, 'name': 'warning--turn-right--g1', 'supercategory': 'warning'},
                 {'id': 34,
                  'name': 'regulatory--turn-left--g3',
                  'supercategory': 'regulatory'},
                 {'id': 35,
                  'name': 'complementary--distance--g1',
                  'supercategory': 'complementary'},
                 {'id': 36,
                  'name': 'regulatory--no-heavy-goods-vehicles--g5',
                  'supercategory': 'regulatory'},
                 {'id': 37,
                  'name': 'regulatory--pedestrians-only--g2',
                  'supercategory': 'regulatory'},
                 {'id': 38, 'name': 'warning--narrow-bridge--g1', 'supercategory': 'warning'},
                 {'id': 39,
                  'name': 'regulatory--no-stopping--g5',
                  'supercategory': 'regulatory'},
                 {'id': 40, 'name': 'warning--crossroads--g3', 'supercategory': 'warning'},
                 {'id': 41,
                  'name': 'regulatory--turn-right-ahead--g1',
                  'supercategory': 'regulatory'},
                 {'id': 42,
                  'name': 'regulatory--dual-lanes-go-straight-on-left--g1',
                  'supercategory': 'regulatory'},
                 {'id': 43,
                  'name': 'regulatory--wrong-way--g1',
                  'supercategory': 'regulatory'},
                 {'id': 44,
                  'name': 'complementary--go-right--g2',
                  'supercategory': 'complementary'},
                 {'id': 45,
                  'name': 'regulatory--maximum-speed-limit-led-80--g1',
                  'supercategory': 'regulatory'},
                 {'id': 46,
                  'name': 'warning--railroad-crossing-without-barriers--g1',
                  'supercategory': 'warning'},
                 {'id': 47,
                  'name': 'warning--winding-road-first-right--g1',
                  'supercategory': 'warning'},
                 {'id': 48,
                  'name': 'regulatory--shared-path-pedestrians-and-bicycles--g1',
                  'supercategory': 'regulatory'},
                 {'id': 49,
                  'name': 'regulatory--dual-lanes-go-straight-on-right--g1',
                  'supercategory': 'regulatory'},
                 {'id': 50,
                  'name': 'regulatory--maximum-speed-limit-25--g2',
                  'supercategory': 'regulatory'},
                 {'id': 51, 'name': 'warning--texts--g1', 'supercategory': 'warning'},
                 {'id': 52,
                  'name': 'regulatory--no-motor-vehicles-except-motorcycles--g2',
                  'supercategory': 'regulatory'},
                 {'id': 53, 'name': 'warning--narrow-bridge--g3', 'supercategory': 'warning'},
                 {'id': 54, 'name': 'warning--curve-right--g1', 'supercategory': 'warning'},
                 {'id': 55,
                  'name': 'regulatory--one-way-straight--g1',
                  'supercategory': 'regulatory'},
                 {'id': 56,
                  'name': 'regulatory--no-parking-or-no-stopping--g1',
                  'supercategory': 'regulatory'},
                 {'id': 57,
                  'name': 'regulatory--passing-lane-ahead--g1',
                  'supercategory': 'regulatory'},
                 {'id': 58,
                  'name': 'regulatory--turn-right--g3',
                  'supercategory': 'regulatory'},
                 {'id': 59,
                  'name': 'regulatory--road-closed-to-vehicles--g3',
                  'supercategory': 'regulatory'},
                 {'id': 60,
                  'name': 'regulatory--go-straight-or-turn-right--g1',
                  'supercategory': 'regulatory'},
                 {'id': 61,
                  'name': 'regulatory--no-left-turn--g1',
                  'supercategory': 'regulatory'},
                 {'id': 62,
                  'name': 'warning--dual-lanes-right-turn-or-go-straight--g1',
                  'supercategory': 'warning'},
                 {'id': 63, 'name': 'warning--roadworks--g4', 'supercategory': 'warning'},
                 {'id': 64,
                  'name': 'complementary--trucks-turn-right--g1',
                  'supercategory': 'complementary'},
                 {'id': 65,
                  'name': 'warning--crossroads-with-priority-to-the-right--g1',
                  'supercategory': 'warning'},
                 {'id': 66,
                  'name': 'warning--two-way-traffic--g2',
                  'supercategory': 'warning'},
                 {'id': 67,
                  'name': 'warning--slippery-road-surface--g2',
                  'supercategory': 'warning'},
                 {'id': 68, 'name': 'warning--road-bump--g2', 'supercategory': 'warning'},
                 {'id': 69,
                  'name': 'regulatory--end-of-priority-road--g1',
                  'supercategory': 'regulatory'},
                 {'id': 70,
                  'name': 'information--motorway--g1',
                  'supercategory': 'information'},
                 {'id': 71,
                  'name': 'regulatory--no-heavy-goods-vehicles--g2',
                  'supercategory': 'regulatory'},
                 {'id': 72,
                  'name': 'warning--winding-road-first-right--g3',
                  'supercategory': 'warning'},
                 {'id': 73,
                  'name': 'information--pedestrians-crossing--g1',
                  'supercategory': 'information'},
                 {'id': 74,
                  'name': 'warning--pedestrians-crossing--g4',
                  'supercategory': 'warning'},
                 {'id': 75,
                  'name': 'warning--railroad-crossing--g4',
                  'supercategory': 'warning'},
                 {'id': 76,
                  'name': 'regulatory--go-straight-or-turn-left--g3',
                  'supercategory': 'regulatory'},
                 {'id': 77,
                  'name': 'regulatory--no-parking-or-no-stopping--g5',
                  'supercategory': 'regulatory'},
                 {'id': 78, 'name': 'warning--curve-right--g2', 'supercategory': 'warning'},
                 {'id': 79,
                  'name': 'regulatory--maximum-speed-limit-5--g1',
                  'supercategory': 'regulatory'},
                 {'id': 80,
                  'name': 'complementary--chevron-right--g3',
                  'supercategory': 'complementary'},
                 {'id': 81,
                  'name': 'regulatory--no-parking-or-no-stopping--g2',
                  'supercategory': 'regulatory'},
                 {'id': 82,
                  'name': 'regulatory--maximum-speed-limit-10--g1',
                  'supercategory': 'regulatory'},
                 {'id': 83, 'name': 'regulatory--no-buses--g3', 'supercategory': 'regulatory'},
                 {'id': 84,
                  'name': 'regulatory--pass-on-either-side--g1',
                  'supercategory': 'regulatory'},
                 {'id': 85, 'name': 'regulatory--yield--g1', 'supercategory': 'regulatory'},
                 {'id': 86,
                  'name': 'regulatory--keep-right--g2',
                  'supercategory': 'regulatory'},
                 {'id': 87,
                  'name': 'complementary--distance--g3',
                  'supercategory': 'complementary'},
                 {'id': 88,
                  'name': 'information--dead-end--g1',
                  'supercategory': 'information'},
                 {'id': 89,
                  'name': 'warning--added-lane-right--g1',
                  'supercategory': 'warning'},
                 {'id': 90,
                  'name': 'regulatory--go-straight--g1',
                  'supercategory': 'regulatory'},
                 {'id': 91, 'name': 'warning--stop-ahead--g1', 'supercategory': 'warning'},
                 {'id': 92, 'name': 'warning--curve-left--g1', 'supercategory': 'warning'},
                 {'id': 93,
                  'name': 'complementary--except-bicycles--g1',
                  'supercategory': 'complementary'},
                 {'id': 94,
                  'name': 'warning--traffic-merges-right--g2',
                  'supercategory': 'warning'},
                 {'id': 95,
                  'name': 'regulatory--maximum-speed-limit-120--g1',
                  'supercategory': 'regulatory'},
                 {'id': 96,
                  'name': 'regulatory--parking-restrictions--g2',
                  'supercategory': 'regulatory'},
                 {'id': 97,
                  'name': 'information--bike-route--g1',
                  'supercategory': 'information'},
                 {'id': 98,
                  'name': 'complementary--chevron-right--g5',
                  'supercategory': 'complementary'},
                 {'id': 99,
                  'name': 'regulatory--no-motor-vehicles-except-motorcycles--g1',
                  'supercategory': 'regulatory'},
                 {'id': 100, 'name': 'warning--t-roads--g2', 'supercategory': 'warning'},
                 {'id': 101,
                  'name': 'regulatory--keep-right--g4',
                  'supercategory': 'regulatory'},
                 {'id': 102,
                  'name': 'warning--road-narrows-left--g2',
                  'supercategory': 'warning'},
                 {'id': 103,
                  'name': 'regulatory--no-overtaking--g4',
                  'supercategory': 'regulatory'},
                 {'id': 104,
                  'name': 'complementary--go-right--g1',
                  'supercategory': 'complementary'},
                 {'id': 105,
                  'name': 'regulatory--no-right-turn--g2',
                  'supercategory': 'regulatory'},
                 {'id': 106,
                  'name': 'warning--road-narrows-right--g2',
                  'supercategory': 'warning'},
                 {'id': 107,
                  'name': 'complementary--chevron-right--g2',
                  'supercategory': 'complementary'},
                 {'id': 108,
                  'name': 'regulatory--no-parking--g1',
                  'supercategory': 'regulatory'},
                 {'id': 109, 'name': 'warning--y-roads--g1', 'supercategory': 'warning'},
                 {'id': 110,
                  'name': 'regulatory--no-motorcycles--g2',
                  'supercategory': 'regulatory'},
                 {'id': 111,
                  'name': 'regulatory--go-straight--g3',
                  'supercategory': 'regulatory'},
                 {'id': 112,
                  'name': 'regulatory--maximum-speed-limit-70--g1',
                  'supercategory': 'regulatory'},
                 {'id': 113,
                  'name': 'regulatory--no-overtaking--g5',
                  'supercategory': 'regulatory'},
                 {'id': 114,
                  'name': 'regulatory--no-u-turn--g3',
                  'supercategory': 'regulatory'},
                 {'id': 115,
                  'name': 'regulatory--maximum-speed-limit-110--g1',
                  'supercategory': 'regulatory'},
                 {'id': 116,
                  'name': 'warning--junction-with-a-side-road-acute-left--g1',
                  'supercategory': 'warning'},
                 {'id': 117,
                  'name': 'complementary--maximum-speed-limit-35--g1',
                  'supercategory': 'complementary'},
                 {'id': 118, 'name': 'warning--roadworks--g6', 'supercategory': 'warning'},
                 {'id': 119,
                  'name': 'regulatory--one-way-left--g1',
                  'supercategory': 'regulatory'},
                 {'id': 120,
                  'name': 'complementary--both-directions--g2',
                  'supercategory': 'complementary'},
                 {'id': 121,
                  'name': 'regulatory--stop-here-on-red-or-flashing-light--g1',
                  'supercategory': 'regulatory'},
                 {'id': 122,
                  'name': 'regulatory--no-turn-on-red--g2',
                  'supercategory': 'regulatory'},
                 {'id': 123,
                  'name': 'warning--slippery-road-surface--g1',
                  'supercategory': 'warning'},
                 {'id': 124,
                  'name': 'complementary--chevron-right--g1',
                  'supercategory': 'complementary'},
                 {'id': 125,
                  'name': 'complementary--both-directions--g1',
                  'supercategory': 'complementary'},
                 {'id': 126, 'name': 'regulatory--stop--g10', 'supercategory': 'regulatory'},
                 {'id': 127,
                  'name': 'complementary--maximum-speed-limit-75--g1',
                  'supercategory': 'complementary'},
                 {'id': 128,
                  'name': 'warning--traffic-signals--g3',
                  'supercategory': 'warning'},
                 {'id': 129,
                  'name': 'regulatory--no-overtaking--g1',
                  'supercategory': 'regulatory'},
                 {'id': 130, 'name': 'warning--school-zone--g2', 'supercategory': 'warning'},
                 {'id': 131,
                  'name': 'complementary--chevron-right--g4',
                  'supercategory': 'complementary'},
                 {'id': 132, 'name': 'warning--road-bump--g1', 'supercategory': 'warning'},
                 {'id': 133,
                  'name': 'regulatory--priority-over-oncoming-vehicles--g1',
                  'supercategory': 'regulatory'},
                 {'id': 134,
                  'name': 'complementary--maximum-speed-limit-55--g1',
                  'supercategory': 'complementary'},
                 {'id': 135,
                  'name': 'warning--traffic-signals--g1',
                  'supercategory': 'warning'},
                 {'id': 136,
                  'name': 'complementary--one-direction-left--g1',
                  'supercategory': 'complementary'},
                 {'id': 137,
                  'name': 'information--parking--g5',
                  'supercategory': 'information'},
                 {'id': 138,
                  'name': 'warning--pedestrians-crossing--g12',
                  'supercategory': 'warning'},
                 {'id': 139,
                  'name': 'regulatory--no-right-turn--g1',
                  'supercategory': 'regulatory'},
                 {'id': 140,
                  'name': 'regulatory--maximum-speed-limit-100--g3',
                  'supercategory': 'regulatory'},
                 {'id': 141,
                  'name': 'complementary--turn-right--g2',
                  'supercategory': 'complementary'},
                 {'id': 142, 'name': 'warning--children--g1', 'supercategory': 'warning'},
                 {'id': 143,
                  'name': 'regulatory--maximum-speed-limit-45--g3',
                  'supercategory': 'regulatory'},
                 {'id': 144,
                  'name': 'warning--traffic-merges-left--g1',
                  'supercategory': 'warning'},
                 {'id': 145,
                  'name': 'complementary--tow-away-zone--g1',
                  'supercategory': 'complementary'},
                 {'id': 146,
                  'name': 'regulatory--one-way-right--g3',
                  'supercategory': 'regulatory'},
                 {'id': 147,
                  'name': 'regulatory--give-way-to-oncoming-traffic--g1',
                  'supercategory': 'regulatory'},
                 {'id': 148,
                  'name': 'regulatory--no-parking--g5',
                  'supercategory': 'regulatory'},
                 {'id': 149,
                  'name': 'regulatory--pass-on-either-side--g2',
                  'supercategory': 'regulatory'},
                 {'id': 150,
                  'name': 'regulatory--no-turn-on-red--g1',
                  'supercategory': 'regulatory'},
                 {'id': 151,
                  'name': 'regulatory--no-parking--g2',
                  'supercategory': 'regulatory'},
                 {'id': 152,
                  'name': 'information--parking--g2',
                  'supercategory': 'information'},
                 {'id': 153,
                  'name': 'regulatory--keep-right--g6',
                  'supercategory': 'regulatory'},
                 {'id': 154,
                  'name': 'regulatory--no-motorcycles--g1',
                  'supercategory': 'regulatory'},
                 {'id': 155, 'name': 'warning--roadworks--g2', 'supercategory': 'warning'},
                 {'id': 156,
                  'name': 'regulatory--pedestrians-only--g1',
                  'supercategory': 'regulatory'},
                 {'id': 157,
                  'name': 'information--living-street--g1',
                  'supercategory': 'information'},
                 {'id': 158,
                  'name': 'warning--domestic-animals--g1',
                  'supercategory': 'warning'},
                 {'id': 159,
                  'name': 'information--interstate-route--g1',
                  'supercategory': 'information'},
                 {'id': 160,
                  'name': 'warning--divided-highway-ends--g1',
                  'supercategory': 'warning'},
                 {'id': 161,
                  'name': 'regulatory--bicycles-only--g1',
                  'supercategory': 'regulatory'},
                 {'id': 162,
                  'name': 'information--gas-station--g3',
                  'supercategory': 'information'},
                 {'id': 163,
                  'name': 'warning--flaggers-in-road--g1',
                  'supercategory': 'warning'},
                 {'id': 164,
                  'name': 'information--disabled-persons--g1',
                  'supercategory': 'information'},
                 {'id': 165,
                  'name': 'information--children--g1',
                  'supercategory': 'information'},
                 {'id': 166,
                  'name': 'warning--junction-with-a-side-road-perpendicular-right--g3',
                  'supercategory': 'warning'},
                 {'id': 167,
                  'name': 'regulatory--do-not-block-intersection--g1',
                  'supercategory': 'regulatory'},
                 {'id': 168,
                  'name': 'complementary--maximum-speed-limit-15--g1',
                  'supercategory': 'complementary'},
                 {'id': 169, 'name': 'warning--roadworks--g3', 'supercategory': 'warning'},
                 {'id': 170,
                  'name': 'regulatory--reversible-lanes--g2',
                  'supercategory': 'regulatory'},
                 {'id': 171,
                  'name': 'regulatory--no-heavy-goods-vehicles--g4',
                  'supercategory': 'regulatory'},
                 {'id': 172,
                  'name': 'regulatory--end-of-no-parking--g1',
                  'supercategory': 'regulatory'},
                 {'id': 173,
                  'name': 'regulatory--no-entry--g1',
                  'supercategory': 'regulatory'},
                 {'id': 174,
                  'name': 'warning--pedestrians-crossing--g5',
                  'supercategory': 'warning'},
                 {'id': 175,
                  'name': 'information--highway-interstate-route--g2',
                  'supercategory': 'information'},
                 {'id': 176,
                  'name': 'information--safety-area--g2',
                  'supercategory': 'information'},
                 {'id': 177,
                  'name': 'complementary--maximum-speed-limit-25--g1',
                  'supercategory': 'complementary'},
                 {'id': 178,
                  'name': 'regulatory--keep-left--g1',
                  'supercategory': 'regulatory'},
                 {'id': 179,
                  'name': 'complementary--keep-right--g1',
                  'supercategory': 'complementary'},
                 {'id': 180,
                  'name': 'complementary--pass-right--g1',
                  'supercategory': 'complementary'},
                 {'id': 181,
                  'name': 'warning--railroad-crossing--g1',
                  'supercategory': 'warning'},
                 {'id': 182,
                  'name': 'regulatory--one-way-right--g2',
                  'supercategory': 'regulatory'},
                 {'id': 183,
                  'name': 'warning--junction-with-a-side-road-perpendicular-left--g1',
                  'supercategory': 'warning'},
                 {'id': 184,
                  'name': 'complementary--maximum-speed-limit-30--g1',
                  'supercategory': 'complementary'},
                 {'id': 185,
                  'name': 'regulatory--no-u-turn--g1',
                  'supercategory': 'regulatory'},
                 {'id': 186,
                  'name': 'warning--junction-with-a-side-road-perpendicular-left--g3',
                  'supercategory': 'warning'},
                 {'id': 187, 'name': 'warning--wild-animals--g1', 'supercategory': 'warning'},
                 {'id': 188,
                  'name': 'regulatory--no-overtaking-by-heavy-goods-vehicles--g1',
                  'supercategory': 'regulatory'},
                 {'id': 189,
                  'name': 'warning--railroad-crossing-without-barriers--g3',
                  'supercategory': 'warning'},
                 {'id': 190,
                  'name': 'regulatory--mopeds-and-bicycles-only--g1',
                  'supercategory': 'regulatory'},
                 {'id': 191,
                  'name': 'warning--trucks-crossing--g1',
                  'supercategory': 'warning'},
                 {'id': 192,
                  'name': 'regulatory--triple-lanes-turn-left-center-lane--g1',
                  'supercategory': 'regulatory'},
                 {'id': 193,
                  'name': 'regulatory--go-straight-or-turn-left--g1',
                  'supercategory': 'regulatory'},
                 {'id': 194,
                  'name': 'regulatory--keep-right--g1',
                  'supercategory': 'regulatory'},
                 {'id': 195,
                  'name': 'information--highway-exit--g1',
                  'supercategory': 'information'},
                 {'id': 196,
                  'name': 'warning--junction-with-a-side-road-acute-right--g1',
                  'supercategory': 'warning'},
                 {'id': 197, 'name': 'warning--roundabout--g1', 'supercategory': 'warning'},
                 {'id': 198,
                  'name': 'regulatory--go-straight-or-turn-right--g3',
                  'supercategory': 'regulatory'},
                 {'id': 199,
                  'name': 'warning--double-turn-first-right--g1',
                  'supercategory': 'warning'},
                 {'id': 200,
                  'name': 'complementary--one-direction-right--g1',
                  'supercategory': 'complementary'},
                 {'id': 201,
                  'name': 'regulatory--go-straight-or-turn-left--g2',
                  'supercategory': 'regulatory'},
                 {'id': 202,
                  'name': 'regulatory--no-bicycles--g2',
                  'supercategory': 'regulatory'},
                 {'id': 203, 'name': 'warning--texts--g2', 'supercategory': 'warning'},
                 {'id': 204,
                  'name': 'complementary--chevron-left--g5',
                  'supercategory': 'complementary'},
                 {'id': 205,
                  'name': 'regulatory--maximum-speed-limit-led-60--g1',
                  'supercategory': 'regulatory'},
                 {'id': 206,
                  'name': 'warning--pass-left-or-right--g2',
                  'supercategory': 'warning'},
                 {'id': 207,
                  'name': 'regulatory--no-parking-or-no-stopping--g3',
                  'supercategory': 'regulatory'},
                 {'id': 208,
                  'name': 'warning--double-reverse-curve-right--g1',
                  'supercategory': 'warning'},
                 {'id': 209,
                  'name': 'warning--kangaloo-crossing--g1',
                  'supercategory': 'warning'},
                 {'id': 210,
                  'name': 'regulatory--dual-path-bicycles-and-pedestrians--g1',
                  'supercategory': 'regulatory'},
                 {'id': 211,
                  'name': 'warning--height-restriction--g2',
                  'supercategory': 'warning'},
                 {'id': 212,
                  'name': 'warning--bicycles-crossing--g1',
                  'supercategory': 'warning'},
                 {'id': 213,
                  'name': 'regulatory--maximum-speed-limit-90--g1',
                  'supercategory': 'regulatory'},
                 {'id': 214,
                  'name': 'warning--horizontal-alignment-right--g1',
                  'supercategory': 'warning'},
                 {'id': 215,
                  'name': 'information--limited-access-road--g1',
                  'supercategory': 'information'},
                 {'id': 216, 'name': 'warning--roadworks--g1', 'supercategory': 'warning'},
                 {'id': 217,
                  'name': 'regulatory--maximum-speed-limit-20--g1',
                  'supercategory': 'regulatory'},
                 {'id': 218,
                  'name': 'warning--double-curve-first-left--g1',
                  'supercategory': 'warning'},
                 {'id': 219,
                  'name': 'regulatory--maximum-speed-limit-55--g2',
                  'supercategory': 'regulatory'},
                 {'id': 220,
                  'name': 'complementary--chevron-left--g1',
                  'supercategory': 'complementary'},
                 {'id': 221, 'name': 'warning--road-widens--g1', 'supercategory': 'warning'},
                 {'id': 222,
                  'name': 'regulatory--maximum-speed-limit-35--g2',
                  'supercategory': 'regulatory'},
                 {'id': 223,
                  'name': 'complementary--maximum-speed-limit-40--g1',
                  'supercategory': 'complementary'},
                 {'id': 224,
                  'name': 'regulatory--no-stopping--g1',
                  'supercategory': 'regulatory'},
                 {'id': 225,
                  'name': 'warning--railroad-crossing-without-barriers--g4',
                  'supercategory': 'warning'},
                 {'id': 226,
                  'name': 'regulatory--maximum-speed-limit-40--g1',
                  'supercategory': 'regulatory'},
                 {'id': 227, 'name': 'warning--crossroads--g1', 'supercategory': 'warning'},
                 {'id': 228,
                  'name': 'warning--railroad-crossing--g3',
                  'supercategory': 'warning'},
                 {'id': 229,
                  'name': 'warning--hairpin-curve-right--g1',
                  'supercategory': 'warning'},
                 {'id': 230,
                  'name': 'regulatory--maximum-speed-limit-30--g3',
                  'supercategory': 'regulatory'},
                 {'id': 231,
                  'name': 'regulatory--stop-here-on-red-or-flashing-light--g2',
                  'supercategory': 'regulatory'},
                 {'id': 232, 'name': 'regulatory--stop--g2', 'supercategory': 'regulatory'},
                 {'id': 233, 'name': 'other-sign', 'supercategory': 'other-sign'},
                 {'id': 234,
                  'name': 'regulatory--maximum-speed-limit-50--g1',
                  'supercategory': 'regulatory'},
                 {'id': 235,
                  'name': 'complementary--turn-left--g2',
                  'supercategory': 'complementary'},
                 {'id': 236,
                  'name': 'warning--junction-with-a-side-road-perpendicular-right--g1',
                  'supercategory': 'warning'},
                 {'id': 237,
                  'name': 'information--parking--g6',
                  'supercategory': 'information'},
                 {'id': 238, 'name': 'warning--texts--g3', 'supercategory': 'warning'},
                 {'id': 239,
                  'name': 'information--end-of-motorway--g1',
                  'supercategory': 'information'},
                 {'id': 240,
                  'name': 'information--airport--g2',
                  'supercategory': 'information'},
                 {'id': 241, 'name': 'warning--roundabout--g2', 'supercategory': 'warning'},
                 {'id': 242, 'name': 'regulatory--stop--g1', 'supercategory': 'regulatory'},
                 {'id': 243, 'name': 'warning--other-danger--g1', 'supercategory': 'warning'},
                 {'id': 244, 'name': 'warning--road-narrows--g2', 'supercategory': 'warning'},
                 {'id': 245,
                  'name': 'information--airport--g1',
                  'supercategory': 'information'},
                 {'id': 246,
                  'name': 'information--emergency-facility--g2',
                  'supercategory': 'information'},
                 {'id': 247,
                  'name': 'regulatory--maximum-speed-limit-30--g1',
                  'supercategory': 'regulatory'},
                 {'id': 248,
                  'name': 'regulatory--no-pedestrians--g1',
                  'supercategory': 'regulatory'},
                 {'id': 249,
                  'name': 'regulatory--shared-path-bicycles-and-pedestrians--g1',
                  'supercategory': 'regulatory'},
                 {'id': 250,
                  'name': 'warning--falling-rocks-or-debris-right--g2',
                  'supercategory': 'warning'},
                 {'id': 251,
                  'name': 'regulatory--maximum-speed-limit-100--g1',
                  'supercategory': 'regulatory'},
                 {'id': 252, 'name': 'warning--turn-left--g1', 'supercategory': 'warning'},
                 {'id': 253,
                  'name': 'regulatory--end-of-prohibition--g1',
                  'supercategory': 'regulatory'},
                 {'id': 254,
                  'name': 'information--bus-stop--g1',
                  'supercategory': 'information'},
                 {'id': 255,
                  'name': 'warning--double-curve-first-right--g1',
                  'supercategory': 'warning'},
                 {'id': 256,
                  'name': 'warning--road-widens-right--g1',
                  'supercategory': 'warning'},
                 {'id': 257,
                  'name': 'information--gas-station--g1',
                  'supercategory': 'information'},
                 {'id': 258,
                  'name': 'regulatory--bicycles-only--g2',
                  'supercategory': 'regulatory'},
                 {'id': 259,
                  'name': 'regulatory--one-way-left--g2',
                  'supercategory': 'regulatory'},
                 {'id': 260,
                  'name': 'information--parking--g1',
                  'supercategory': 'information'},
                 {'id': 261, 'name': 'regulatory--u-turn--g1', 'supercategory': 'regulatory'},
                 {'id': 262,
                  'name': 'information--end-of-built-up-area--g1',
                  'supercategory': 'information'},
                 {'id': 263,
                  'name': 'warning--traffic-merges-right--g1',
                  'supercategory': 'warning'},
                 {'id': 264,
                  'name': 'warning--railroad-intersection--g3',
                  'supercategory': 'warning'},
                 {'id': 265,
                  'name': 'complementary--chevron-left--g4',
                  'supercategory': 'complementary'},
                 {'id': 266,
                  'name': 'regulatory--no-straight-through--g1',
                  'supercategory': 'regulatory'},
                 {'id': 267,
                  'name': 'complementary--obstacle-delineator--g1',
                  'supercategory': 'complementary'},
                 {'id': 268,
                  'name': 'regulatory--road-closed--g2',
                  'supercategory': 'regulatory'},
                 {'id': 269,
                  'name': 'warning--trail-crossing--g2',
                  'supercategory': 'warning'},
                 {'id': 270,
                  'name': 'warning--two-way-traffic--g1',
                  'supercategory': 'warning'},
                 {'id': 271,
                  'name': 'regulatory--turn-right--g1',
                  'supercategory': 'regulatory'},
                 {'id': 272, 'name': 'warning--steep-descent--g2', 'supercategory': 'warning'},
                 {'id': 273,
                  'name': 'regulatory--turn-left--g2',
                  'supercategory': 'regulatory'},
                 {'id': 274,
                  'name': 'regulatory--one-way-right--g1',
                  'supercategory': 'regulatory'},
                 {'id': 275,
                  'name': 'complementary--keep-left--g1',
                  'supercategory': 'complementary'},
                 {'id': 276, 'name': 'information--food--g2', 'supercategory': 'information'},
                 {'id': 277,
                  'name': 'complementary--distance--g2',
                  'supercategory': 'complementary'},
                 {'id': 278,
                  'name': 'regulatory--priority-road--g1',
                  'supercategory': 'regulatory'},
                 {'id': 279,
                  'name': 'regulatory--no-overtaking--g2',
                  'supercategory': 'regulatory'},
                 {'id': 280,
                  'name': 'regulatory--maximum-speed-limit-led-100--g1',
                  'supercategory': 'regulatory'},
                 {'id': 281, 'name': 'warning--road-narrows--g1', 'supercategory': 'warning'},
                 {'id': 282,
                  'name': 'warning--railroad-crossing-with-barriers--g1',
                  'supercategory': 'warning'},
                 {'id': 283,
                  'name': 'warning--winding-road-first-left--g1',
                  'supercategory': 'warning'},
                 {'id': 284,
                  'name': 'complementary--maximum-speed-limit-45--g1',
                  'supercategory': 'complementary'},
                 {'id': 285,
                  'name': 'regulatory--one-way-left--g3',
                  'supercategory': 'regulatory'},
                 {'id': 286,
                  'name': 'complementary--chevron-left--g2',
                  'supercategory': 'complementary'},
                 {'id': 287,
                  'name': 'warning--road-narrows-left--g1',
                  'supercategory': 'warning'},
                 {'id': 288,
                  'name': 'regulatory--end-of-speed-limit-zone--g1',
                  'supercategory': 'regulatory'},
                 {'id': 289,
                  'name': 'warning--emergency-vehicles--g1',
                  'supercategory': 'warning'},
                 {'id': 290,
                  'name': 'complementary--maximum-speed-limit-20--g1',
                  'supercategory': 'complementary'},
                 {'id': 291,
                  'name': 'regulatory--stop-signals--g1',
                  'supercategory': 'regulatory'},
                 {'id': 292,
                  'name': 'regulatory--road-closed-to-vehicles--g1',
                  'supercategory': 'regulatory'},
                 {'id': 293,
                  'name': 'complementary--maximum-speed-limit-70--g1',
                  'supercategory': 'complementary'},
                 {'id': 294,
                  'name': 'warning--bicycles-crossing--g2',
                  'supercategory': 'warning'},
                 {'id': 295,
                  'name': 'information--pedestrians-crossing--g2',
                  'supercategory': 'information'},
                 {'id': 296,
                  'name': 'regulatory--keep-left--g2',
                  'supercategory': 'regulatory'},
                 {'id': 297,
                  'name': 'regulatory--roundabout--g1',
                  'supercategory': 'regulatory'},
                 {'id': 298,
                  'name': 'regulatory--no-turn-on-red--g3',
                  'supercategory': 'regulatory'},
                 {'id': 299,
                  'name': 'warning--double-curve-first-left--g2',
                  'supercategory': 'warning'},
                 {'id': 300,
                  'name': 'regulatory--no-parking--g6',
                  'supercategory': 'regulatory'},
                 {'id': 301,
                  'name': 'information--telephone--g2',
                  'supercategory': 'information'},
                 {'id': 302,
                  'name': 'complementary--chevron-left--g3',
                  'supercategory': 'complementary'},
                 {'id': 303,
                  'name': 'warning--pedestrians-crossing--g1',
                  'supercategory': 'warning'},
                 {'id': 304,
                  'name': 'regulatory--turn-right--g2',
                  'supercategory': 'regulatory'},
                 {'id': 305,
                  'name': 'warning--road-narrows-right--g1',
                  'supercategory': 'warning'},
                 {'id': 306,
                  'name': 'warning--pedestrians-crossing--g10',
                  'supercategory': 'warning'},
                 {'id': 307,
                  'name': 'information--trailer-camping--g1',
                  'supercategory': 'information'},
                 {'id': 308,
                  'name': 'regulatory--no-vehicles-carrying-dangerous-goods--g1',
                  'supercategory': 'regulatory'},
                 {'id': 309,
                  'name': 'warning--railroad-crossing-with-barriers--g2',
                  'supercategory': 'warning'},
                 {'id': 310,
                  'name': 'regulatory--maximum-speed-limit-60--g1',
                  'supercategory': 'regulatory'},
                 {'id': 311,
                  'name': 'regulatory--height-limit--g1',
                  'supercategory': 'regulatory'},
                 {'id': 312,
                  'name': 'regulatory--maximum-speed-limit-40--g3',
                  'supercategory': 'regulatory'},
                 {'id': 313,
                  'name': 'regulatory--maximum-speed-limit-80--g1',
                  'supercategory': 'regulatory'}]


if __name__=='__main__':
    ds = MTSDataset()
    ds.convert_dataset()